POST http://localhost:3003/walks/create
Content-Type: application/json

{
    "data": "2022/06/28",
    "duracao": "30",
    "latitude": 25624735,
    "longitude": 25673587,
    "hora_inicio": "17:00:00",
    "hora_fim": "17:30:00",
    "pets": ["Olivia", "Thor"],
    "tutor": "Déborah"
}

###

POST http://localhost:3003/walks/create
Content-Type: application/json

{
    "data": "2022/06/29",
    "duracao": "30",
    "latitude": 12346585,
    "longitude": 87653399,
    "hora_inicio": "18:00:00",
    "hora_fim": "18:30:00",
    "pets": ["Nina"],
    "tutor": "Hugo"
}

###

GET http://localhost:3003/pets
Content-Type: application/json

{
    "nome": "Olivia",
    "tutor": "Déborah"
}

###

GET http://localhost:3003/walks
Content-Type: application/json

###

PUT http://localhost:3003/walks/finish/23ea0868-1ccc-4af6-a263-760a8c534bd3
Content-Type: application/json

###

PUT http://localhost:3003/walks/start/23ea0868-1ccc-4af6-a263-760a8c534bd3
Content-Type: application/json