GET http://localhost:3003/users
Content-Type: application/json

###

POST http://localhost:3003/users
Content-Type: application/json

{
    "id": 10,
    "name": "Barbara",
    "email": "iunersiwmow",
    "type": "ADMIN",
    "age": 38
}

###

PUT http://localhost:3003/users/10
Content-Type: application/json

{
    "id": 10,
    "name": "Barbara-ALTERADO",
    "email": "iunersiwmow",
    "type": "ADMIN",
    "age": 38
}

###

PATCH  http://localhost:3003/users/10
Content-Type: application/json

{
    "name": "Barbara-REALTERADO"
}

###

DELETE http://localhost:3003/users/10
