POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name":"Olivia",
    "email":"pimpa@lab.com",
    "password":"pimpa123"
}

###

POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name":"Manu",
    "email":"manu@lab.com",
    "password":"manu123"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email":"Flabio@lab.com",
    "password":"flabio123"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email":"hugo@lab.com",
    "password":"hugo123"
}

###

POST http://localhost:3003/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMzhkMTkxLWJhYzAtNGUyYi05NzYwLWM5ZjFiYmJhNzc0ZSIsImlhdCI6MTY1MTc2NDIzOSwiZXhwIjoxNjUxNzY1Njc5fQ.mWjcysLwVjoBMTqVc1PALnNmrDY09LfBplNAU4RzemE

{
    "photo": "https://picsum.photos/200/300",
    "description": "Qualquer",
    "role": "NORMAL"
}

###

GET http://localhost:3003/posts/feed
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMzhkMTkxLWJhYzAtNGUyYi05NzYwLWM5ZjFiYmJhNzc0ZSIsImlhdCI6MTY1MTg0NTkyNywiZXhwIjoxNjUxODQ3MzY3fQ.-0p_Ru_mdlZQSYN65MWmopL7lWtTBzBWPY2mPNV3oFM

###

GET Http://localhost:3003/posts/90181613-2fe9-44a2-bead-9ea9e7cf5d71
Content-Type: application/json

###

POST http://localhost:3003/users/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMzhkMTkxLWJhYzAtNGUyYi05NzYwLWM5ZjFiYmJhNzc0ZSIsImlhdCI6MTY1MTg0NDM3OSwiZXhwIjoxNjUxODQ1ODE5fQ.3PwGboLhp_e_c4_Zs75ebKnfZ9FrihCXqG-7FRRCf9E

{
    "userToFollowId": "63670133-149a-49f3-9471-c684da340db2"
}

###

POST http://localhost:3003/users/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNGJhZTE4LTNiNTktNDgwNC05OThiLTZhMmI5Y2M4MjFkZCIsImlhdCI6MTY1MTc2MDE1NiwiZXhwIjoxNjUxNzYxNTk2fQ.p-mMOSRR5a0wos7AANjuJ-Pmt0iMiMxDhEyRcyOJsZ4

{
    "userToUnfollowId": "fd4bae18-3b59-4804-998b-6a2b9cc821dd"
}