POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name":"Hugo",
    "email":"hugo@lab.com",
    "password":"hugo123"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email":"Flabio@lab.com",
    "password":"flabio123"
}

###

POST http://localhost:3003/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNGJhZTE4LTNiNTktNDgwNC05OThiLTZhMmI5Y2M4MjFkZCIsImlhdCI6MTY1MTY5NjU3MCwiZXhwIjoxNjUxNjk4MDEwfQ.CNSrl200QEuGjXwNbXctFESw55J66x-jVM3hen2qDLA

{
    "photo": "https://picsum.photos/id/237/200/300",
    "description": "Doguinho",
    "role": "NORMAL"
}

###

GET http://localhost:3003/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNGJhZTE4LTNiNTktNDgwNC05OThiLTZhMmI5Y2M4MjFkZCIsImlhdCI6MTY1MTY5NjU3MCwiZXhwIjoxNjUxNjk4MDEwfQ.CNSrl200QEuGjXwNbXctFESw55J66x-jVM3hen2qDLA

###

GET Http://localhost:3003/posts/90181613-2fe9-44a2-bead-9ea9e7cf5d71
Content-Type: application/json

###

POST http://localhost:3003/users/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMzhkMTkxLWJhYzAtNGUyYi05NzYwLWM5ZjFiYmJhNzc0ZSIsImlhdCI6MTY1MTcxODU3MiwiZXhwIjoxNjUxNzIwMDEyfQ.BmtYSGdtRw_gaZ-oBCmp8CIqraHQwzBRaN2199FOkVk

{
    "userToFollowId": "fd4bae18-3b59-4804-998b-6a2b9cc821dd"
}